config/routes.rb
Geocoder::Application.routes.draw do
  resources :http_requests

  get 'location' => 'http_requests#find'
  get 'safelocation' => 'http_requests#find_safe'
end

app/models/http_request.rb
class HttpRequest < ActiveRecord::Base
  geocoded_by :full_street_address
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/http_requests_controller.rb
class HttpRequestsController < ApplicationController
  before_action :set_http_request, only: [:show, :edit, :update, :destroy]

  # GET /http_requests
  # GET /http_requests.json
  def index
    @http_requests = HttpRequest.all
  end

  # GET /http_requests/1
  # GET /http_requests/1.json
  def show
  end

  # GET /http_requests/new
  def new
    @http_request = HttpRequest.new
  end

  # GET /http_requests/1/edit
  def edit
  end

  # POST /http_requests
  # POST /http_requests.json
  def create
    @http_request = HttpRequest.new(http_request_params)

    respond_to do |format|
      if @http_request.save
        format.html { redirect_to @http_request, notice: 'Http request was successfully created.' }
        format.json { render action: 'show', status: :created, location: @http_request }
      else
        format.html { render action: 'new' }
        format.json { render json: @http_request.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /http_requests/1
  # PATCH/PUT /http_requests/1.json
  def update
    respond_to do |format|
      if @http_request.update(http_request_params)
        format.html { redirect_to @http_request, notice: 'Http request was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @http_request.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /http_requests/1
  # DELETE /http_requests/1.json
  def destroy
    @http_request.destroy
    respond_to do |format|
      format.html { redirect_to http_requests_url }
      format.json { head :no_content }
    end
  end

  def find
    result = request.location
    render json:result
  end

  def find_safe
    result = request.safe_location
    render json:result
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_http_request
      @http_request = HttpRequest.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def http_request_params
      params.require(:http_request).permit(:ip, :address)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/http_requests_helper.rb
module HttpRequestsHelper
end

app/views/http_requests/_form.html.erb
<%= form_for(@http_request) do |f| %>
  <% if @http_request.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@http_request.errors.count, "error") %> prohibited this http_request from being saved:</h2>

      <ul>
      <% @http_request.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :ip %><br>
    <%= f.text_field :ip %>
  </div>
  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_field :address %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/http_requests/edit.html.erb
<h1>Editing http_request</h1>

<%= render 'form' %>

<%= link_to 'Show', @http_request %> |
<%= link_to 'Back', http_requests_path %>

app/views/http_requests/index.html.erb
<h1>Listing http_requests</h1>

<table>
  <thead>
    <tr>
      <th>Ip</th>
      <th>Address</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @http_requests.each do |http_request| %>
      <tr>
        <td><%= http_request.ip %></td>
        <td><%= http_request.address %></td>
        <td><%= link_to 'Show', http_request %></td>
        <td><%= link_to 'Edit', edit_http_request_path(http_request) %></td>
        <td><%= link_to 'Destroy', http_request, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Http request', new_http_request_path %>

app/views/http_requests/new.html.erb
<h1>New http_request</h1>

<%= render 'form' %>

<%= link_to 'Back', http_requests_path %>

app/views/http_requests/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Ip:</strong>
  <%= @http_request.ip %>
</p>

<p>
  <strong>Address:</strong>
  <%= @http_request.address %>
</p>

<%= link_to 'Edit', edit_http_request_path(@http_request) %> |
<%= link_to 'Back', http_requests_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Geocoder</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>